version: '3'
services:
  application:
    build:
      context: .
      dockerfile: application/docker/Dockerfile
    image: ossaijad/phpapp:latest
    networks:
     - appnet
    volumes:
      - ./application/src:/var/www/html
  application-gateway:
    build:
      context: .
      dockerfile: gateway/docker/Dockerfile
    image: ossaijad/phpappgateway:latest
    ports:
     - "8080:80"
    networks:
     - appnet
    depends_on:
      - server
    volumes:
      - ./application/src:/var/www/html
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
     
  networks:
    appnet:
      driver: "bridge"
  volumes:
    data:
      driver: "local"
