version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile
    image: ossaijad/server:latest
    networks:
     - appnet
    volumes:
      - ./server/application:/var/www/html
  server-nginx:
    build:
      context: .
      dockerfile: gateway/docker/Dockerfile
    image: ossaijad/servergateway:latest
    ports:
     - "8080:80"
    networks:
     - appnet
    depends_on:
      - server
    volumes:
      - ./server/application:/var/www/html
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
  networks:
    appnet:
      driver: "bridge"
  volumes:
    data:
      driver: "local"
